name: Merge to master or develop

on:
  push:
    branches: [master, develop]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

concurrency:
  group: merge-develop
  cancel-in-progress: false

jobs:
  build_documentation:
    name: macOS Docs Deployment
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
      - name: Build Basilisk
        uses: ./.github/actions/build
        with:
          python-version: 3.13
          conan-args: --opNav True --allOptPkg --mujoco True --mujocoReplay True
      - name: Build docs
        uses: ./.github/actions/docs
      - name: Deploy master branch merges to /
        if: success() && github.ref_name == 'master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          destination_dir: .
          keep_files: true
      - name: Deploy develop branch merges to /develop
        if: success() && github.ref_name == 'develop'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          destination_dir: develop
          keep_files: true
