name: Merge to develop

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

concurrency:
  group: merge-develop
  cancel-in-progress: false

jobs:
  build_documentation:
    name: macOS Docs Deployment
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
      - name: Build Basilisk
        uses: ./.github/actions/build
        with:
          python-version: 3.13
          conan-args: --opNav True --allOptPkg --mujoco True --mujocoReplay True
      - name: Build docs
        uses: ./.github/actions/docs
      - name: Deploy
        if: ${{ success() }} # deploy only if prior steps ok
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          force_orphan: true
